### ISSUE TITLE
Can not install packer-post-processor-vhd on ubuntu

### ISSUE THREAD

**Issue by doublefx** [benwebber/packer-post-processor-vhd#3]
Hi, I've been trying to install `packer-post-processor-vhd on my ubuntu machine but got:

go get github.com/benwebber/packer-post-processor-vhd
# github.com/mitchellh/packer/builder/qemu
/home/fred/go/src/github.com/mitchellh/packer/builder/qemu/builder.go:400:14: cannot use sshConfig (type func(multistep.StateBag) (*"github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".ClientConfig, error)) as type func(multistep.StateBag) (*"github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh".ClientConfig, error) in field value
/home/fred/go/src/github.com/mitchellh/packer/builder/qemu/ssh.go:25:35: cannot use "github.com/hashicorp/packer/communicator/ssh".PasswordKeyboardInteractive(config.Comm.SSHPassword) (type "github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh".KeyboardInteractiveChallenge) as type "github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".KeyboardInteractiveChallenge in argument to "github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".KeyboardInteractive
/home/fred/go/src/github.com/mitchellh/packer/builder/qemu/ssh.go:34:39: cannot use signer (type "github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh".Signer) as type "github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".Signer in argument to "github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".PublicKeys:
	"github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh".Signer does not implement "github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".Signer (wrong type for PublicKey method)
		have PublicKey() "github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh".PublicKey
		want PublicKey() "github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".PublicKey
# github.com/mitchellh/packer/builder/virtualbox/common
/home/fred/go/src/github.com/mitchellh/packer/builder/virtualbox/common/ssh.go:26:36: cannot use "github.com/hashicorp/packer/communicator/ssh".PasswordKeyboardInteractive(config.Comm.SSHPassword) (type "github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh".KeyboardInteractiveChallenge) as type "github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".KeyboardInteractiveChallenge in argument to "github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".KeyboardInteractive
/home/fred/go/src/github.com/mitchellh/packer/builder/virtualbox/common/ssh.go:35:40: cannot use signer (type "github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh".Signer) as type "github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".Signer in argument to "github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".PublicKeys:
	"github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh".Signer does not implement "github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".Signer (wrong type for PublicKey method)
		have PublicKey() "github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh".PublicKey
		want PublicKey() "github.com/mitchellh/packer/vendor/golang.org/x/crypto/ssh".PublicKey
# github.com/mitchellh/packer/post-processor/vagrant
/home/fred/go/src/github.com/mitchellh/packer/post-processor/vagrant/post-processor.go:175:11: cannot use &md (type *"github.com/mitchellh/packer/vendor/github.com/mitchellh/mapstructure".Metadata) as type *"github.com/hashicorp/packer/vendor/github.com/mitchellh/mapstructure".Metadata in field value

I'm not a go dev, therefore any help would be greatly appreciated.

-Fred.

**Comment by benwebber** [comment]
Looks like we need to upgrade to new versions of Packer/Packer dependency APIs.

In the meantime, are you able to download and run the Linux/amd64 binary release from <https://github.com/benwebber/packer-post-processor-vhd/releases>?

**Comment by benwebber** [comment]
Even easier. Those errors simply reflected that HashiCorp moved Packer from https://github.com/mitchellh/packer to https://github.com/hashicorp/packer.

Fixed in 43f004b2b834837e6a34d141ed5267b01a952d5c.

**Comment by doublefx** [comment]
Thanks for your quick feedback and I've been able to compile it successfully.
